version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.1-debian-10'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami'
  prestashop:
    image: 'docker.io/bitnami/prestashop:1.7-debian-10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=otus-qa-automation-final_prestashop_1
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb
  selenoid:
    image: aerokube/selenoid
    ports:
      - '4444:4444'
    volumes:
      - '$PWD/selenoid_conf:/etc/selenoid'
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: ['-container-network', 'otus-qa-automation-final_default']

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
